### ISSUE TITLE
Resource starvation at low message volumes

### ISSUE THREAD

**Issue by negz** [spotify/async-google-pubsub-client#14]
We've run into a bug where this client starves itself on resources. The puller threads never gives the acker thread a chance to run and vice versa. We've worked around it by setting the concurrency to 1. This only seems to be an issue when message throughput is very low.

I'm reporting this issue secondhand - I believe @lndbrg discovered it.

**Comment by negz** [comment]
(I've mostly raised this issue for informational purposes, so other's don't have to find out by word of mouth as I did.)

**Comment by robertsutherland** [comment]
@negz I have run into this issue even with the concurrency set to 1. Are there any other workarounds that guarantee message acknowledgement?

**Comment by negz** [comment]
@robertsutherland I'm afraid I don't know of any.

I believe we're moving away from this library internally in favour of Google's new gRPC Pubsub client.

**Comment by i-maravic** [comment]
Fixed by #21 

Released version 1.25 contains the fix.
