### ISSUE TITLE
The type java.util.concurrent.CompletableFuture cannot be resolved. Java 1.7

### ISSUE THREAD

**Issue by kassemshehady** [spotify/async-google-pubsub-client#27]
The type java.util.concurrent.CompletableFuture cannot be resolved. Java 1.7

**Comment by danielnorberg** [comment]
This library requires Java 8.

**Comment by kassemshehady** [comment]
Thanks @danielnorberg, but how you use java 8 with appengine?

**Comment by parkan** [comment]
@kassemshehady you can currently use java 8 in the flexible environment: https://cloud.google.com/appengine/docs/flexible/java/dev-java-only

Support in the standard environment is coming soon/eventually, track it in this issue: https://partnerissuetracker.corp.google.com/issues/35895687#
