### ISSUE TITLE
publisher.close()/publisher.closeFuture().get() should flush client

### ISSUE THREAD

**Issue by bitkid** [spotify/async-google-pubsub-client#37]
at least that's what i would expect :) i just modified testPullBatch in PubsubIT. should this test pass?

https://gist.github.com/bitkid/0ccc45d8d58dcf2b1ca88f9f9ed9dec6

**Comment by danielnorberg** [comment]
Use the future returned by `publish()` to ensure that the message publication completed before closing the publisher.

**Comment by bitkid** [comment]
ok thx
